# https://docs.travis-ci.com/user/languages/csharp/#.NET-Core

language: csharp

# Don't build other branches than master
branches:
  only:
    - master

matrix:
  include:
    # Ref: https://docs.travis-ci.com/user/reference/osx/
    # Ref: https://docs.travis-ci.com/user/reference/trusty/
    - os: linux
      dist: trusty
      sudo: required
      mono: latest
      env: 
        - OS=linux
        - TARGET=mono
    - os: osx
      mono: latest
      env: 
        - OS=osx
        - TARGET=mono

install:
  - nuget restore src/mono-test.sln

script:
  - msbuild /p:Configuration=Debug src/mono-test.sln

deploy:
  # TODO update `api_key.secure`
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # - Encrypt it: `travis encrypt 0123456789012345678901234567890123456789
  # - Paste the output down here
  api_key:
    secure: a2oTHiMtrhes5ruVZUBbiXmBu/A+tn1LaWHfFT80TCSdK+442RQnnZWZju9a5/nnbWB2H+46fHxFbR651Bz+bllw/TFTlagjT5hGoa/w7zvg6l5AvfZ/NS1JFhQgLN0Z5t0GqF5pXemytZs3ACPCHNmGAX2r3/B0G2vf7bOXq3Xg20YPh0sGK/uJFjnDlL1Q+DS+9HoX2Rh4lwbvpMUL9Q1zC7ZWfyJOwz5/ZkR+t9ZEY6YcJOov331wt+DFcpV1XNiy4AZvYsG3M5gOG/YH62/kpqsFq9pOryXkjWha0R3hdDfNdPU3kUqmDBaPbWJI3Qsz/08qWeaD4nlHHDj9FVISRFaBSisyr84khdauSpN6HuFiH3S6pd5wFRukWadeHTfSUfvWY8DVkYVATyw2KlYPldVBI6sMRjtvLiOcclmd4/eyiVdt6rgJIkbwI6HgUd5YAtUaYnu36+ktWa3ZtLIhgGfEi5PPwzIYhmM7aK9fWT1Yk0SoKS11iHXLsVK/PkKAt4YqETv+ljwr2dl0I/lwxm0flyLy93tBIR5jwYWycSaL3Uf709sSMelaVtiySWlpVpLrtRP2f7ZvJt+xbTrgH539Th0pYuHujVIUbxkNLfnFqSuAvXDAvYe+krC1j85DQOvXAJ8w+guljJTClmPjf6V1fMWV8betlmS6REs=
  file_glob: true
  file:
    - src/bin/Debug/*
  on:
    condition: $OS = osx
    branch: master
    tags: true
  provider: releases
  skip_cleanup: true

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master
