#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 1.0.{build}

branches:
  only:
    - master
  except:
    - gh-pages


#---------------------------------#
#    environment configuration    #
#---------------------------------#

matrix:
  fast_finish: true

os: Visual Studio 2017

platform:
  - x64

configuration:
  - Debug

init:
  - git config --global core.autocrlf true


build_script:
    - cmd: >-
        msbuild src/mono-test.sln /t:Rebuild /p:Configuration=Release;Platform=x64 /m
        
test_script:
    - cmd: >-
        echo "test not enabled yet"
